name: brian_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  font_awesome_flutter: ^10.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/kopi1.jpg
    - assets/kopi2.jpg
    - assets/kopi3.jpg
    - assets/promo1.jpg
    - assets/promo2.jpg
    - assets/promo3.jpg
    - assets/arabica.jpg
    - assets/robusta.jpg
    - assets/espresso.jpg
